### PR TITLE
Analyze phenotypes - from zhou

### PR DESCRIPTION
**Pull request by yuanzhou**
This pull request contains many small UI changes based on the discussion at https://github.com/monarch-initiative/monarch-app/issues/1250. As I explained to @jmcmurry, it's considered as a quick and dirty fix for the release purpose.

There are still couple things need to be addressed after the release:
- Fix gene autocomplete bug
- Add species to filter out phenotypes when creating the phenotype profile
- Make Step 2 predefined target groups checkboxes instead of dropdown menu

@harryhoch @kshefchek please review and merge the PR if it looks good. Thanks!

### CODE REVIEW

**Comment by yuanzhou** [comment]
@kshefchek do you have a chance to merge this PR? @jmcmurry I remember you said the they wanted to show the updated Analyze Phenotypes ASAP.

**Comment by kshefchek** [comment]
Sure I can take a look.  For 8515544 is there a reason we're removing the test rather than fixing it?  This used to test the compare setting on the analyze page.

**Comment by yuanzhou** [comment]
@kshefchek I tried to fix that test and couldn't figure out the reason why it was failed. It worked on my local. And another reason is I thought since I'll continue to make changes, it's better to add some new behave tests once I finalize the changes.

**Comment by yuanzhou** [comment]
The commit which caused the behave test to fail is displaying a green check now.

capture

After I added back the origional behave test, it still failed.

**Comment by yuanzhou** [comment]
@DoctorBud I think we can merge this PR and ignore the behave test failure for now. Because it still failed even after I commented out that test. And I saw a different error from this build history: https://travis-ci.org/monarch-initiative/monarch-app/builds/143150102

screen shot 2016-07-07 at 8 56 58 pm

**Comment by kshefchek** [comment]
@yuanzhou try pulling from master, that should fix it.

**Comment by yuanzhou** [comment]
@kshefchek I pulled from master and that old behave test still failed again. I did see `IL10` inside the `phen_vis_svg_group` both on beta and my localhost.

capture

**Comment by yuanzhou** [comment]
@kshefchek @DoctorBud disabled that behave test again to get a green check.

**Pull request merged**
