### PR TITLE
Disclaimer and license update

### PR DESCRIPTION
**Pull request by jmcmurry**
Adding disclaimer page to the pages, navbar, and basic behave test. Not sure if blog-scratch-base.mustache was necessary but updated that too just in case. Fixes https://github.com/monarch-initiative/monarch-app/issues/216

### CODE REVIEW

**Comment by kltm** [comment]
@jmcmurry Not really about this PR in particular, but I wanted to point to the FDA's API's ToS for an interesting take on something similar: https://open.fda.gov/terms/ .

**Comment by jmcmurry** [comment]
@kltm could you please do a sanity check on the engineering of it and merge if it looks ok please? The verbiage is already approved, thanks.

**Comment by kltm** [comment]
Eyeballing, it looks fine. Although, apparently, the units tests were not happy.

**Comment by jmcmurry** [comment]
Yeah, there was some weirdness unrelated to my PR. When owsim rebuilds, I will tweak by branch and try again.

**Comment by kshefchek** [comment]
When I run it locally I get a 404 for /page/disclaimer and /about/disclaimer.  @jmcmurry could you take a closer look at webapp.js?  It might be a wiring issue.

**Comment by kshefchek** [comment]
@jmcmurry could you take a second pass at this?  There are some small styling issues, see https://beta.monarchinitiative.org/page/disclaimer

**Pull request merged**
