### PR TITLE
fix taxon bug in compare call

### PR DESCRIPTION
**Pull request by kshefchek**
Fixes issue with gene taxon not showing up in compare results

### CODE REVIEW

**Comment by jmcmurry** [comment]
yay! this is huge, thanks

**Comment by frdougal** [comment]
@kshefchek  That's great.  Currently I can retrieve the taxon for Homo sapiens genes only.  The taxon is stored as an object with two attributes: id (NCBITaxon:9606) and label (Homo sapiens).  Will your changes follow the same approach?

**Comment by kshefchek** [comment]
@cborromeo correct, let me know if it doesn't work.

**Comment by frdougal** [comment]
@kshefchek can I use the non-production servers for solr?  I think Jeremy was still working on the servers.  Can I access them using the connections in server_config_dev.json?

**Comment by kshefchek** [comment]
@cborromeo it's probably easier to continue to develop using the production servers for now.  Hopefully we can unpassword protect the dev servers soon.

**Pull request merged**
