### PR TITLE
Analyze phenotypes fix

### PR DESCRIPTION
**Pull request by yuanzhou**
1. Fixed compare to make it work with phenogrid
2. Hided upload section (exomiser)
3. Added limit in search section, and only show limit field for single species selection
4. Added a new behave test case for all species search

@kshefchek This PR integrates the changes in monarch-app analyze/phenotype page, more deeper changes are made in phenogrid repo, I'll send another PR in phenogrid to @harryhoch for his review.

I didn't add behave test for compare section since the compare api issues have not been addressed.

(See https://github.com/monarch-initiative/phenogrid/issues/203 for detailed discussions)

### CODE REVIEW

**Comment by kshefchek** [comment]
@yuanzhou looks great!  My only suggestion is that we add a test in for the compare functionality as well.

**Comment by yuanzhou** [comment]
@kshefchek I've added a new compare behave test from a working example. The Travis CI check didn't pass because the phenogrid updates haven't been updated yet by updating the phenogrid npm version number. I'll push the changes to npmjs.org once Harry merges the phenogrid PR. Then I can update the phenogrid version number in package.json.

**Comment by yuanzhou** [comment]
@kshefchek any chance that you can help me check out the added behave test? 

```

@data
 Scenario: compare phenotypes with geneList
    Given I go to page "/analyze/phenotypes"
     and I type "micro" into the phenotype analyze search
     and I wait until "Microalbuminuria" appears in the autocomplete
     and I click the autocomplete item "Microalbuminuria"
     and I type "micro" into the phenotype analyze search
     and I wait until "microcephaly" appears in the autocomplete
     and I click the autocomplete item "microcephaly"
     and I click the "compare" radio button
     and I input the following text into the textarea "gene-list"
     """
     NCBIGene:388552,NCBIGene:12166
     """
     when I submit analyze phenotype
     then the document should contain "BLOC1S3"
```

this one failed, not sure what caused that.

**Comment by yuanzhou** [comment]
I also tried to add a new rule:

```
@given('I input "{text}" into the textarea "{eid}"')
def step_impl(context, text, eid):
    webelt = context.browser.find_element_by_id(eid)
    webelt.send_keys(text)
```

and changed the test scenario to 

```
@data
 Scenario: compare phenotype with geneList
    Given I go to page "/analyze/phenotypes"
     and I type "micro" into the phenotype analyze search
     and I wait until "Microalbuminuria" appears in the autocomplete
     and I click the autocomplete item "Microalbuminuria"
     and I click the "compare" radio button
     and I input "NCBIGene:388552,NCBIGene:12166" into the textarea "gene-list"
     when I submit analyze phenotype
     then the document should contain "BLOC1S3"
```

But still failed. Tested in my local server, failed too. No clue. It worked when I manually went through the steps.

**Comment by kshefchek** [comment]
+1

**Comment by yuanzhou** [comment]
@kshefchek Thanks for fixing the behave test and merging the PR. I still don't understand why we have to specify the "pg_svg_group" instead of finding that "BLOC1S3" text directly. Because the "search all" test doesn't wait for that "pg_svg_group"

**Pull request merged**
