### PR TITLE
Update main.mustache

### PR DESCRIPTION
**Pull request by jmcmurry**
Until this link is actually live again on the ohsu deployment, we should take this out.
http://mail.monarchinitiative.org/mailman/listinfo/users
Related to https://github.com/monarch-initiative/monarch-app/issues/1203
@ethan @DoctorBud please advise.

### CODE REVIEW

**Comment by kshefchek** [comment]
+1

**Comment by jmcmurry** [comment]
@ethan @DoctorBud? Thanks

**Comment by DoctorBud** [comment]
+1
Go ahead and merge it.

**Comment by kshefchek** [comment]
+1

**Pull request merged**
