### PR TITLE
update orgs on footer

### PR DESCRIPTION
**Pull request by lwinfree**

### CODE REVIEW

**Comment by lwinfree** [comment]
@kshefchek my checks are failing on this one too - same checks failing as my other PR. Please let me know if I need to change anything/can help with the failing checks!

**Comment by DoctorBud** [comment]
Did you test the app to see how this footer looks? I'm concerned it will make the footer quite large vertically and that we should verify that it doesn't affect pages with footers. IMHO, a footer should be less than 10% of the 'visible' page height if we are putting it on every page. Otherwise, it's just annoying.

**Comment by lwinfree** [comment]
@DoctorBud Yeah I checked it out & got a second opinion from @jmcmurry. I agree with you that it seems pretty big...I'm open to ideas for making it smaller.

**Comment by jmcmurry** [comment]
Given how many institutions are involved (and growing), I'm open to linking to the team page rather than listing all.

**Comment by DoctorBud** [comment]
My latest PR, https://github.com/monarch-initiative/monarch-app/pull/1515, included these changes to footer.mustache, so this particular PR is no longer necessary. I am closing it.

**Pull request closed without merging**
