### PR TITLE
Remove cruft

### PR DESCRIPTION
**Pull request by cmungall**
Clearing cruft that I am 99% sure is unused, see #975

### CODE REVIEW

**Comment by DoctorBud** [comment]
+1
It's satisfying to see dead code go away.

Not sure what's going on with the failing tests, but both of the failures are in code that is loading a Phenogrid. There are two modes of failure that I've observed:
- The data URL that Phenogrid is using is broken, so that Phenogrid cannot load. This happens when Phenogrid is pointing at the beta GOLR or SciGraph servers and they are down for some reason.
- The virtual window size is too short for the Phenogrid SVG element to be visible, so that Selenium/Firefox fails to find it. See https://github.com/monarch-initiative/monarch-app/issues/1291 for more info. In theory, you have my fix from this PR https://github.com/monarch-initiative/monarch-app/pull/1289

**Comment by jmcmurry** [comment]
@harryhoch @yuanzhou could you please look into this? Thank you :)

**Comment by harryhoch** [comment]
@yuanzhou, do you have a few minutes to review? Thanks

**Comment by DoctorBud** [comment]
One thing that might be causing this is if Phenogrid is referring to one of the 'dev' SciGraph or GOLR servers that is currently under a username/password regime due to UDP data. Since Phenogrid accesses these servers without logging, we can't see that fact from the Travis logs. So it might be worth verifying that Phenogrid doesn't have any hardcoded server references in its code. All of PG's config should derived from the config that the monarch-app is using, currently:

```
Starting server. Platform: NodeJS. Environment: beta. Port: 8080.
NODEVERSION: v4.4.1
defaultConfigFile: conf/server_config_beta.json golrConfigFile: conf/golr-conf.json
defaultConfig: {"type":"beta","app_base":"https://beta.monarchinitiative.org","scigraph_url":"https://scigraph-ontology.monarchinitiative.org/scigraph/","scigraph_data_url":"https://scigraph-data.monarchinitiative.org/scigraph/","golr_url":"https://solr.monarchinitiative.org/solr/golr/","owlsim_services_url":"https://monarchinitiative.org/owlsim","analytics_id":""}
#USE_LOG_FETCH enabled
#USE_BUNDLE enabled
bbop.monarch.Engine Using pre-set configuration: 
bbop.monarch.Engine Using pre-set golr configuration: 
HapiJS Server running at: http://0.0.0.0:8080
```

If PG is pointing at https://scigraph-ontology-dev.monarchinitiative.org or https://solr-dev.monarchinitiative.org/, then it is incorrect (but this has happened in the past), and it will fail due to username/password.

**Comment by yuanzhou** [comment]
Not sure if this is the cause, I went to https://beta.monarchinitiative.org/ and the login popup showed up to ask me username and password. It says 401 "Authorization Required".

**Comment by kshefchek** [comment]
We had to change the monarch_base setting in the conf so phenogrid could access monarch app from the browser.  The build is fixed now.

**Pull request merged**
