### PR TITLE
Update team to include Lilly Winfree

### PR DESCRIPTION
**Pull request by jmcmurry**
Adding Lilly to team page and updating Shahim to alum status.

### CODE REVIEW

**Comment by jmcmurry** [comment]
@DoctorBud I only just noticed that the [master no longer has a monarch-team.json file](https://github.com/monarch-initiative/monarch-app/tree/master/conf). Did you remove the requirement for this yaml to json conversion? If so great, but just want to be aware AND I should remove the conversion instructions from the file header of monarch-team.yaml. Thanks :)

**Comment by jmcmurry** [comment]
Otherwise should be ready to merge. cc: @lwinfree

**Comment by DoctorBud** [comment]
There should be no monarch-team.json file stored in GitHub. It is generated by `gulp build` from the monarch-team.yaml file. Please remove monarch-team.json from this PR. You should only edit the source yaml file and replace that in GitHub (along with the new picture).

**Comment by jmcmurry** [comment]
OK thanks Dan; should be all set now. Please confirm and merge if ok.

**Comment by jmcmurry** [comment]
@DoctorBud please merge if all ok.

**Comment by lwinfree** [comment]
My info isn't showing on the website team page, and Shahim is not listed as an alum. I'm not sure how to fix this... @jmcmurry or @DoctorBud any ideas/help? Thanks!

**Comment by jmcmurry** [comment]
Hi Lilly, this is all set on beta (https://beta.monarchinitiative.org/page/team). Please make sure everything looks ok then we will push to production. This push is typically done in bundles of changes rather than one unless there's a big issue. @DoctorBud, @kshefchek, @jnguyenx anyone know of anything in the UI currently in the works or should we just push to production now?

**Comment by jnguyenx** [comment]
I got nothing new for the UI on my side.

**Comment by mellybelly** [comment]
any chance we might squeeze in an info page on MME before the meetings this week?
there is a ticket

**Comment by jmcmurry** [comment]
That depends on @kshefchek

**Comment by lwinfree** [comment]
Ahhh this makes more sense now! I was trying to figure out why it wasn't showing up, but couldn't see that we had done anything incorrectly. Thanks for the info!

**Comment by kshefchek** [comment]
>> That depends on @kshefchek

Apologies @jmcmurry, I may have lost something in the shuffle, what am I blocking?

**Pull request merged**
