### PR TITLE
Fix exac

### PR DESCRIPTION
**Pull request by putmantime**

### CODE REVIEW

**Comment by putmantime** [comment]
Fix in response to https://github.com/monarch-initiative/monarch-app/issues/1574 where mygene was assuming all numerical ids were entrez ids.  Now supports mapping to HGNC, Ensembl, OMIM, and Entrez

**Comment by kshefchek** [comment]
+1

**Comment by vgainullin** [comment]
I am still seeing this issue, another example below: 
https://monarchinitiative.org/gene/HGNC:3581
http://exac.broadinstitute.org/gene/ENSG00000171634

**Comment by kshefchek** [comment]
This has not yet been pushed production, but you can see the changes on our beta site: https://beta.monarchinitiative.org/gene/HGNC:3581

**Pull request merged**
