### PR TITLE
Genome feature integration

### PR DESCRIPTION
**Pull request by nathandunn**
Its Raw @kshefchek .  Very raw. 

screen shot 2017-09-29 at 5 12 21 pm

### CODE REVIEW

**Comment by nathandunn** [comment]
- [x] pull in changes from widget
- [ ] autoresize
- [x] grab species from taxon in mygene to get the correct gene info
- [x] fix externalUrl
- [x] test with non-mod species 

- [x] remove console.log

===
- [ ] refactor to lib to allow parameterized components, etc.

**Comment by nathandunn** [comment]
@kshefchek  / @DoctorBud   I'm going to plug away to get it working the way I want.  Should be done today.   Won't work for all species, but should work for the main ones.

**Comment by nathandunn** [comment]
Tax IDs here: http://docs.mygene.info/en/latest/doc/data.html#species

**Comment by nathandunn** [comment]
Okay.  I think its good enough for production.   Another developer is working on making it into a library, which we can integrate when that happens.  For now, this is better than what is there (which is nothing).

**Comment by jmcmurry** [comment]
https://github.com/monarch-initiative/impact/issues/65

**Comment by kshefchek** [comment]
+1, would be nice if we could interact with it, but a great improvement.

**Review by kshefchek — APPROVED** [review]

**Comment by nathandunn** [comment]
@kshefchek  Agreed.  But it is simple D3 / SVG code, so please feel free to add to it.   I just wanted to add an initial cut.

**Comment by kshefchek** [comment]
This looks a little different from the screenshot (I probably should have checked that gene), is this right?
https://beta.monarchinitiative.org/gene/ZFIN:ZDB-GENE-001103-2

**Comment by nathandunn** [comment]
screen shot 2017-10-03 at 6 26 41 pm

**Comment by nathandunn** [comment]
Here is the missing commit: https://github.com/monarch-initiative/monarch-app/pull/1504

Sorry, thought I'd pushed it.

**Pull request merged**
